# Generated by Django 3.0.8 on 2020-07-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SweetCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='First name')),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='media')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
